version: '3.8'

services:
  digital-twin:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
    env_file:
      - backend/.env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./logs:/app/logs
      # Mount your Obsidian vault (adjust path as needed)
      # - /path/to/your/vault:/vault:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching and background tasks
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # Optional: PostgreSQL database
  # postgres:
  #   image: postgres:15
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=digitaltwin
  #     - POSTGRES_USER=digitaltwin
  #     - POSTGRES_PASSWORD=changeme
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  # redis_data:
  # postgres_data:
